# Request Examples
# 
# Single arrival, single task, no resources
#
POST http://localhost:8080/API
Content-Type: application/json

{
  "arrivals" : [
    {
      "name" : "Example1",
      "flow" : {
        "ITask" : {
          "name" : "T1",
          "duration" : {
            "IConstant" : {
              "value" : 1.0
            }
          },
          "cost" : {
            "IConstant" : {
              "value" : 2.0
            }
          },
          "resources" : [
          ],
          "priority" : 0
        }
      },
      "rate" : {
        "IConstant" : {
          "value" : 0.0
        }
      },
      "limit" : 1
    }
  ],
  "resources" : [
  ],
  "timeLimit" : null
} 
 
# 
# Single arrival, 2 tasks, no resources
#
POST http://localhost:8080/API
Content-Type: application/json

{
  "arrivals" : [
    {
      "name" : "Example1",
      "flow" : {
        "IThen" : {  
          "args": [
          {
            "ITask" : {
              "name" : "T1",
              "duration" : {
                "IConstant" : {
                  "value" : 1.0
                }
              },
              "cost" : {
                "IConstant" : {
                  "value" : 2.0
                }
              },
              "resources" : [
              ],
              "priority" : 0
            }
          },
          {
            "ITask" : {
              "name" : "T2",
              "duration" : {
                "IConstant" : {
                  "value" : 2.0
                }
              },
              "cost" : {
                "IConstant" : {
                  "value" : 3.0
                }
              },
              "resources" : [
              ],
              "priority" : 0
            }
          }
          ]       
        }
      },
      "rate" : {
        "IConstant" : {
          "value" : 0.0
        }
      },
      "limit" : 1
    }
  ],
  "resources" : [
  ],
  "timeLimit" : null
} 
