sbt "project proter" "runMain com.workflowfm.proter.Evaluation examples/1/1.bpmn proter/src/main/resources/examples/1/proter/modelData.json EvaluationOutput/1 2000 20";
sbt "project proter" "runMain com.workflowfm.proter.Evaluation examples/2/2.bpmn proter/src/main/resources/examples/2/proter/modelData.json EvaluationOutput/2 2000 20";
sbt "project proter" "runMain com.workflowfm.proter.Evaluation examples/3/3.bpmn proter/src/main/resources/examples/3/proter/modelData.json EvaluationOutput/3 2000 20";
sbt "project proter" "runMain com.workflowfm.proter.Evaluation examples/4/4.bpmn proter/src/main/resources/examples/4/proter/modelData.json EvaluationOutput/4 2000 20";
sbt "project proter" "runMain com.workflowfm.proter.Evaluation examples/5/5.bpmn proter/src/main/resources/examples/5/proter/modelData.json EvaluationOutput/5 2000 20";
sbt "project proter" "runMain com.workflowfm.proter.Evaluation examples/6/6.bpmn proter/src/main/resources/examples/6/proter/modelData.json EvaluationOutput/6 2000 20";
sbt "project proter" "runMain com.workflowfm.proter.Evaluation examples/7/7.bpmn proter/src/main/resources/examples/7/proter/modelData.json EvaluationOutput/7 1500 15";
sbt "project proter" "runMain com.workflowfm.proter.Evaluation examples/8/8.bpmn proter/src/main/resources/examples/8/proter/modelData.json EvaluationOutput/8 3000 30";
sbt "project proter" "runMain com.workflowfm.proter.Evaluation examples/9/9.bpmn proter/src/main/resources/examples/9/proter/modelData.json EvaluationOutput/9 3000 30";
sbt "project proter" "runMain com.workflowfm.proter.Evaluation examples/10/10.bpmn proter/src/main/resources/examples/10/proter/modelData.json EvaluationOutput/10 3000 30";
sbt "project proter" "runMain com.workflowfm.proter.Evaluation examples/11/11.bpmn proter/src/main/resources/examples/11/proter/modelData.json EvaluationOutput/11 1500 15";
sbt "project proter" "runMain com.workflowfm.proter.Evaluation examples/12/12.bpmn proter/src/main/resources/examples/12/proter/modelData.json EvaluationOutput/12 1500 15";
sbt "project proter" "runMain com.workflowfm.proter.Evaluation examples/13/13.bpmn proter/src/main/resources/examples/13/proter/modelData.json EvaluationOutput/13 1500 15";
sbt "project proter" "runMain com.workflowfm.proter.Evaluation examples/14/14.bpmn proter/src/main/resources/examples/14/proter/modelData.json EvaluationOutput/14 1500 15";
sbt "project proter" "runMain com.workflowfm.proter.Evaluation examples/15/15.bpmn proter/src/main/resources/examples/15/proter/modelData.json EvaluationOutput/15 4000 40";
sbt "project proter" "runMain com.workflowfm.proter.Evaluation examples/16/16.bpmn proter/src/main/resources/examples/16/proter/modelData.json EvaluationOutput/16 4000 40";
sbt "project proter" "runMain com.workflowfm.proter.Evaluation examples/17/17.bpmn proter/src/main/resources/examples/17/proter/modelData.json EvaluationOutput/17 4000 40";
sbt "project proter" "runMain com.workflowfm.proter.Evaluation examples/18/18.bpmn proter/src/main/resources/examples/18/proter/modelData.json EvaluationOutput/18 4000 40";
sbt "project proter" "runMain com.workflowfm.proter.Evaluation examples/19/19.bpmn proter/src/main/resources/examples/19/proter/modelData.json EvaluationOutput/19 4000 40";
sbt "project proter" "runMain com.workflowfm.proter.Evaluation examples/20/20.bpmn proter/src/main/resources/examples/20/proter/modelData.json EvaluationOutput/20 5000 50";
sbt "project proter" "runMain com.workflowfm.proter.Evaluation examples/21/21.bpmn proter/src/main/resources/examples/21/proter/modelData.json EvaluationOutput/21 1500 0.066 1";
sbt "project proter" "runMain com.workflowfm.proter.Evaluation examples/22/22.bpmn proter/src/main/resources/examples/22/proter/modelData.json EvaluationOutput/22 1500 15";
sbt "project proter" "runMain com.workflowfm.proter.Evaluation examples/23/23.bpmn proter/src/main/resources/examples/23/proter/modelData.json EvaluationOutput/23 1500 0.066 1";
sbt "project proter" "runMain com.workflowfm.proter.Evaluation examples/24/24.bpmn proter/src/main/resources/examples/24/proter/modelData.json EvaluationOutput/24 1500 15";
sbt "project proter" "runMain com.workflowfm.proter.Evaluation examples/25/25.bpmn proter/src/main/resources/examples/25/proter/modelData.json EvaluationOutput/25 1500 15";
sbt "project proter" "runMain com.workflowfm.proter.Evaluation examples/26/26.bpmn proter/src/main/resources/examples/26/proter/modelData.json EvaluationOutput/26 1500 15";
sbt "project proter" "runMain com.workflowfm.proter.Evaluation examples/27/27.bpmn proter/src/main/resources/examples/27/proter/modelData.json EvaluationOutput/27 13 100";
sbt "project proter" "runMain com.workflowfm.proter.Evaluation examples/28/28.bpmn proter/src/main/resources/examples/28/proter/modelData.json EvaluationOutput/28 15 100";
