pages = [{"l":"index.html","n":"proter-root","t":"proter-root","d":"","k":"static"},
{"l":"com/workflowfm/proter.html","n":"com.workflowfm.proter","t":"package com.workflowfm.proter","d":"com/workflowfm/proter","k":"package"},
{"l":"com/workflowfm/proter/Arrival.html","n":"Arrival","t":"class Arrival(time: Long, rate: Distribution, simulationGenerator: SimulationRefGenerator, limit: Option[Int], count: Int) extends DiscreteEvent","d":"com/workflowfm/proter/Arrival","k":"class"},
{"l":"com/workflowfm/proter/Arrival.html","n":"classOrder","t":"val classOrder: Short","d":"com/workflowfm/proter/Arrival","k":"val"},
{"l":"com/workflowfm/proter/Arrival.html","n":"next","t":"def next(): Arrival","d":"com/workflowfm/proter/Arrival","k":"def"},
{"l":"com/workflowfm/proter/AsyncSimulation.html","n":"AsyncSimulation","t":"trait AsyncSimulation extends Simulation","d":"com/workflowfm/proter/AsyncSimulation","k":"trait"},
{"l":"com/workflowfm/proter/AsyncSimulation.html","n":"Callback","t":"type Callback = Try[(TaskInstance, Long)] => Unit","d":"com/workflowfm/proter/AsyncSimulation","k":"type"},
{"l":"com/workflowfm/proter/AsyncSimulation.html","n":"callback","t":"def callback(f: (TaskInstance, Long) => Unit): Callback","d":"com/workflowfm/proter/AsyncSimulation","k":"def"},
{"l":"com/workflowfm/proter/AsyncSimulation.html","n":"task","t":"def task(t: Task, callback: Callback): Unit","d":"com/workflowfm/proter/AsyncSimulation","k":"def"},
{"l":"com/workflowfm/proter/AsyncSimulation.html","n":"tasks","t":"val tasks: Map[UUID, Callback]","d":"com/workflowfm/proter/AsyncSimulation","k":"val"},
{"l":"com/workflowfm/proter/Constant.html","n":"Constant","t":"class Constant(value: Double) extends Distribution","d":"com/workflowfm/proter/Constant","k":"class"},
{"l":"com/workflowfm/proter/ConstantLong.html","n":"ConstantLong","t":"class ConstantLong(value: Long) extends LongDistribution","d":"com/workflowfm/proter/ConstantLong","k":"class"},
{"l":"com/workflowfm/proter/Coordinator.html","n":"Coordinator","t":"class Coordinator(scheduler: Scheduler, singleThread: Boolean, startingTime: Long)(using x$4: ExecutionContext) extends Manager with HashMapPublisher","d":"com/workflowfm/proter/Coordinator","k":"class"},
{"l":"com/workflowfm/proter/Coordinator.html","n":"addArrival","t":"def addArrival(t: Long, limit: Int, rate: Distribution, simulationGenerator: SimulationRefGenerator): Unit","d":"com/workflowfm/proter/Coordinator","k":"def"},
{"l":"com/workflowfm/proter/Coordinator.html","n":"addArrivalNext","t":"def addArrivalNext(limit: Int, rate: Distribution, simulationGenerator: SimulationRefGenerator): Unit","d":"com/workflowfm/proter/Coordinator","k":"def"},
{"l":"com/workflowfm/proter/Coordinator.html","n":"addArrivalNow","t":"def addArrivalNow(limit: Int, rate: Distribution, simulationGenerator: SimulationRefGenerator): Unit","d":"com/workflowfm/proter/Coordinator","k":"def"},
{"l":"com/workflowfm/proter/Coordinator.html","n":"addInfiniteArrival","t":"def addInfiniteArrival(t: Long, rate: Distribution, simulationGenerator: SimulationRefGenerator): Unit","d":"com/workflowfm/proter/Coordinator","k":"def"},
{"l":"com/workflowfm/proter/Coordinator.html","n":"addInfiniteArrivalNext","t":"def addInfiniteArrivalNext(rate: Distribution, simulationGenerator: SimulationRefGenerator): Unit","d":"com/workflowfm/proter/Coordinator","k":"def"},
{"l":"com/workflowfm/proter/Coordinator.html","n":"addInfiniteArrivalNow","t":"def addInfiniteArrivalNow(rate: Distribution, simulationGenerator: SimulationRefGenerator): Unit","d":"com/workflowfm/proter/Coordinator","k":"def"},
{"l":"com/workflowfm/proter/Coordinator.html","n":"addResource","t":"def addResource(r: TaskResource): Unit","d":"com/workflowfm/proter/Coordinator","k":"def"},
{"l":"com/workflowfm/proter/Coordinator.html","n":"addResources","t":"def addResources(r: Seq[TaskResource]): Unit","d":"com/workflowfm/proter/Coordinator","k":"def"},
{"l":"com/workflowfm/proter/Coordinator.html","n":"addSimulation","t":"def addSimulation(t: Long, simulation: SimulationRef): Unit","d":"com/workflowfm/proter/Coordinator","k":"def"},
{"l":"com/workflowfm/proter/Coordinator.html","n":"addSimulationNow","t":"def addSimulationNow(simulation: SimulationRef): Unit","d":"com/workflowfm/proter/Coordinator","k":"def"},
{"l":"com/workflowfm/proter/Coordinator.html","n":"addSimulations","t":"def addSimulations(sims: Seq[(Long, SimulationRef)]): Unit","d":"com/workflowfm/proter/Coordinator","k":"def"},
{"l":"com/workflowfm/proter/Coordinator.html","n":"addSimulationsNow","t":"def addSimulationsNow(sims: Seq[SimulationRef]): Unit","d":"com/workflowfm/proter/Coordinator","k":"def"},
{"l":"com/workflowfm/proter/Coordinator.html","n":"getTime","t":"def getTime(): Long","d":"com/workflowfm/proter/Coordinator","k":"def"},
{"l":"com/workflowfm/proter/Coordinator.html","n":"id","t":"val id: String","d":"com/workflowfm/proter/Coordinator","k":"val"},
{"l":"com/workflowfm/proter/Coordinator.html","n":"limit","t":"def limit(t: Long): Unit","d":"com/workflowfm/proter/Coordinator","k":"def"},
{"l":"com/workflowfm/proter/Coordinator.html","n":"resourceMap","t":"val resourceMap: Map[String, TaskResource]","d":"com/workflowfm/proter/Coordinator","k":"val"},
{"l":"com/workflowfm/proter/Coordinator.html","n":"start","t":"def start(): Future[Any]","d":"com/workflowfm/proter/Coordinator","k":"def"},
{"l":"com/workflowfm/proter/Coordinator.html","n":"stop","t":"def stop(): Unit","d":"com/workflowfm/proter/Coordinator","k":"def"},
{"l":"com/workflowfm/proter/DiscreteEvent.html","n":"DiscreteEvent","t":"trait DiscreteEvent extends Ordered[DiscreteEvent]","d":"com/workflowfm/proter/DiscreteEvent","k":"trait"},
{"l":"com/workflowfm/proter/DiscreteEvent.html","n":"classOrder","t":"val classOrder: Short","d":"com/workflowfm/proter/DiscreteEvent","k":"val"},
{"l":"com/workflowfm/proter/DiscreteEvent.html","n":"compare","t":"def compare(that: DiscreteEvent): Int","d":"com/workflowfm/proter/DiscreteEvent","k":"def"},
{"l":"com/workflowfm/proter/DiscreteEvent.html","n":"sameClassCompare","t":"def sameClassCompare(that: DiscreteEvent): Int","d":"com/workflowfm/proter/DiscreteEvent","k":"def"},
{"l":"com/workflowfm/proter/DiscreteEvent.html","n":"time","t":"def time: Long","d":"com/workflowfm/proter/DiscreteEvent","k":"def"},
{"l":"com/workflowfm/proter/Distribution.html","n":"Distribution","t":"trait Distribution extends LongDistribution","d":"com/workflowfm/proter/Distribution","k":"trait"},
{"l":"com/workflowfm/proter/Distribution.html","n":"estimate","t":"def estimate: Double","d":"com/workflowfm/proter/Distribution","k":"def"},
{"l":"com/workflowfm/proter/Distribution.html","n":"get","t":"def get: Double","d":"com/workflowfm/proter/Distribution","k":"def"},
{"l":"com/workflowfm/proter/Exponential.html","n":"Exponential","t":"class Exponential(mean: Double) extends Distribution","d":"com/workflowfm/proter/Exponential","k":"class"},
{"l":"com/workflowfm/proter/FinishingTask.html","n":"FinishingTask","t":"class FinishingTask(time: Long, task: TaskInstance) extends DiscreteEvent","d":"com/workflowfm/proter/FinishingTask","k":"class"},
{"l":"com/workflowfm/proter/FinishingTask.html","n":"classOrder","t":"val classOrder: Short","d":"com/workflowfm/proter/FinishingTask","k":"val"},
{"l":"com/workflowfm/proter/FutureTasks.html","n":"FutureTasks","t":"trait FutureTasks","d":"com/workflowfm/proter/FutureTasks","k":"trait"},
{"l":"com/workflowfm/proter/FutureTasks.html","n":"futureTask","t":"def futureTask(t: Task): Future[(TaskInstance, Long)]","d":"com/workflowfm/proter/FutureTasks","k":"def"},
{"l":"com/workflowfm/proter/LongDistribution.html","n":"LongDistribution","t":"trait LongDistribution","d":"com/workflowfm/proter/LongDistribution","k":"trait"},
{"l":"com/workflowfm/proter/LongDistribution.html","n":"getLong","t":"def getLong: Long","d":"com/workflowfm/proter/LongDistribution","k":"def"},
{"l":"com/workflowfm/proter/LongDistribution.html","n":"longEstimate","t":"def longEstimate: Long","d":"com/workflowfm/proter/LongDistribution","k":"def"},
{"l":"com/workflowfm/proter/Lookahead.html","n":"Lookahead","t":"trait Lookahead","d":"com/workflowfm/proter/Lookahead","k":"trait"},
{"l":"com/workflowfm/proter/Lookahead.html","n":"+","t":"def +(function: Map[UUID, Long] => Option[Long], generator: Task): Lookahead","d":"com/workflowfm/proter/Lookahead","k":"def"},
{"l":"com/workflowfm/proter/Lookahead.html","n":"++","t":"def ++(function: Map[UUID, Long] => Option[Long], generators: List[Task]): Lookahead","d":"com/workflowfm/proter/Lookahead","k":"def"},
{"l":"com/workflowfm/proter/Lookahead.html","n":"+>","t":"def +>(sourceID: UUID, generator: Task): Lookahead","d":"com/workflowfm/proter/Lookahead","k":"def"},
{"l":"com/workflowfm/proter/Lookahead.html","n":"+>>","t":"def +>>(source: Set[UUID], generator: Task): Lookahead","d":"com/workflowfm/proter/Lookahead","k":"def"},
{"l":"com/workflowfm/proter/Lookahead.html","n":"-","t":"def -(id: UUID): Lookahead","d":"com/workflowfm/proter/Lookahead","k":"def"},
{"l":"com/workflowfm/proter/Lookahead.html","n":"and","t":"def and(that: Lookahead): Lookahead","d":"com/workflowfm/proter/Lookahead","k":"def"},
{"l":"com/workflowfm/proter/Lookahead.html","n":"getTaskData","t":"def getTaskData(scheduled: Iterable[(UUID, Long)]): Seq[(Task, Long)]","d":"com/workflowfm/proter/Lookahead","k":"def"},
{"l":"com/workflowfm/proter/LookaheadSet.html","n":"LookaheadSet","t":"class LookaheadSet(lookaheadSet: Set[(Map[UUID, Long] => Option[Long], List[Task])]) extends Lookahead","d":"com/workflowfm/proter/LookaheadSet","k":"class"},
{"l":"com/workflowfm/proter/Lookaheads.html","n":"Lookaheads","t":"class Lookaheads(lookaheads: Queue[Lookahead]) extends Lookahead","d":"com/workflowfm/proter/Lookaheads","k":"class"},
{"l":"com/workflowfm/proter/Lookaheads$.html","n":"Lookaheads","t":"object Lookaheads","d":"com/workflowfm/proter/Lookaheads$","k":"object"},
{"l":"com/workflowfm/proter/Lookaheads$.html","n":"apply","t":"def apply(lookaheads: Lookahead*): Lookaheads","d":"com/workflowfm/proter/Lookaheads$","k":"def"},
{"l":"com/workflowfm/proter/LookingAhead.html","n":"LookingAhead","t":"trait LookingAhead extends Simulation","d":"com/workflowfm/proter/LookingAhead","k":"trait"},
{"l":"com/workflowfm/proter/LookingAhead.html","n":"completedTasks","t":"val completedTasks: Set[(UUID, Long)]","d":"com/workflowfm/proter/LookingAhead","k":"val"},
{"l":"com/workflowfm/proter/LookingAhead.html","n":"lookahead","t":"var lookahead: Lookahead","d":"com/workflowfm/proter/LookingAhead","k":"var"},
{"l":"com/workflowfm/proter/Manager.html","n":"Manager","t":"trait Manager","d":"com/workflowfm/proter/Manager","k":"trait"},
{"l":"com/workflowfm/proter/Manager.html","n":"simResponse","t":"def simResponse(response: SimResponse): Unit","d":"com/workflowfm/proter/Manager","k":"def"},
{"l":"com/workflowfm/proter/Manager.html","n":"waitFor","t":"def waitFor(simulation: String): Unit","d":"com/workflowfm/proter/Manager","k":"def"},
{"l":"com/workflowfm/proter/NoLookahead$.html","n":"NoLookahead","t":"object NoLookahead extends Lookahead","d":"com/workflowfm/proter/NoLookahead$","k":"object"},
{"l":"com/workflowfm/proter/SimDone.html","n":"SimDone","t":"class SimDone(simulation: String, result: Try[Any]) extends SimResponse","d":"com/workflowfm/proter/SimDone","k":"class"},
{"l":"com/workflowfm/proter/SimReady.html","n":"SimReady","t":"class SimReady(simulation: String, tasks: Seq[Task], abort: Seq[UUID], lookahead: Lookahead) extends SimResponse","d":"com/workflowfm/proter/SimReady","k":"class"},
{"l":"com/workflowfm/proter/SimResponse.html","n":"SimResponse","t":"trait SimResponse","d":"com/workflowfm/proter/SimResponse","k":"trait"},
{"l":"com/workflowfm/proter/SimResponse.html","n":"simulation","t":"val simulation: String","d":"com/workflowfm/proter/SimResponse","k":"val"},
{"l":"com/workflowfm/proter/Simulation.html","n":"Simulation","t":"trait Simulation extends SimulationRef","d":"com/workflowfm/proter/Simulation","k":"trait"},
{"l":"com/workflowfm/proter/Simulation.html","n":"abort","t":"def abort(ids: UUID*): Unit","d":"com/workflowfm/proter/Simulation","k":"def"},
{"l":"com/workflowfm/proter/Simulation.html","n":"ack","t":"def ack(taskIDs: Seq[UUID]): Unit","d":"com/workflowfm/proter/Simulation","k":"def"},
{"l":"com/workflowfm/proter/Simulation.html","n":"complete","t":"def complete(task: TaskInstance, time: Long): Unit","d":"com/workflowfm/proter/Simulation","k":"def"},
{"l":"com/workflowfm/proter/Simulation.html","n":"done","t":"def done(result: Try[Any]): Unit","d":"com/workflowfm/proter/Simulation","k":"def"},
{"l":"com/workflowfm/proter/Simulation.html","n":"fail","t":"def fail(exception: Throwable): Unit","d":"com/workflowfm/proter/Simulation","k":"def"},
{"l":"com/workflowfm/proter/Simulation.html","n":"getLookahead","t":"def getLookahead(): Lookahead","d":"com/workflowfm/proter/Simulation","k":"def"},
{"l":"com/workflowfm/proter/Simulation.html","n":"ready","t":"def ready(): Unit","d":"com/workflowfm/proter/Simulation","k":"def"},
{"l":"com/workflowfm/proter/Simulation.html","n":"simWait","t":"def simWait(): Unit","d":"com/workflowfm/proter/Simulation","k":"def"},
{"l":"com/workflowfm/proter/Simulation.html","n":"succeed","t":"def succeed(result: Any): Unit","d":"com/workflowfm/proter/Simulation","k":"def"},
{"l":"com/workflowfm/proter/Simulation.html","n":"task","t":"def task(t: Task): Unit","d":"com/workflowfm/proter/Simulation","k":"def"},
{"l":"com/workflowfm/proter/Simulation$.html","n":"Simulation","t":"object Simulation","d":"com/workflowfm/proter/Simulation$","k":"object"},
{"l":"com/workflowfm/proter/Simulation$$SimulationStoppingException.html","n":"SimulationStoppingException","t":"class SimulationStoppingException(cause: Throwable) extends Exception","d":"com/workflowfm/proter/Simulation$$SimulationStoppingException","k":"class"},
{"l":"com/workflowfm/proter/Simulation$$TaskAbortedException.html","n":"TaskAbortedException","t":"class TaskAbortedException(cause: Throwable) extends Exception","d":"com/workflowfm/proter/Simulation$$TaskAbortedException","k":"class"},
{"l":"com/workflowfm/proter/SimulationGenerator.html","n":"SimulationGenerator","t":"trait SimulationGenerator extends SimulationRefGenerator","d":"com/workflowfm/proter/SimulationGenerator","k":"trait"},
{"l":"com/workflowfm/proter/SimulationRef.html","n":"SimulationRef","t":"trait SimulationRef","d":"com/workflowfm/proter/SimulationRef","k":"trait"},
{"l":"com/workflowfm/proter/SimulationRef.html","n":"completed","t":"def completed(time: Long, tasks: Seq[TaskInstance]): Unit","d":"com/workflowfm/proter/SimulationRef","k":"def"},
{"l":"com/workflowfm/proter/SimulationRef.html","n":"name","t":"def name: String","d":"com/workflowfm/proter/SimulationRef","k":"def"},
{"l":"com/workflowfm/proter/SimulationRef.html","n":"run","t":"def run(): Unit","d":"com/workflowfm/proter/SimulationRef","k":"def"},
{"l":"com/workflowfm/proter/SimulationRef.html","n":"stop","t":"def stop(): Unit","d":"com/workflowfm/proter/SimulationRef","k":"def"},
{"l":"com/workflowfm/proter/SimulationRefGenerator.html","n":"SimulationRefGenerator","t":"trait SimulationRefGenerator","d":"com/workflowfm/proter/SimulationRefGenerator","k":"trait"},
{"l":"com/workflowfm/proter/SimulationRefGenerator.html","n":"build","t":"def build(manager: Manager, count: Int): SimulationRef","d":"com/workflowfm/proter/SimulationRefGenerator","k":"def"},
{"l":"com/workflowfm/proter/SingleTaskSimulation.html","n":"SingleTaskSimulation","t":"class SingleTaskSimulation(val name: String, val manager: Manager, resources: Seq[String], duration: LongDistribution, cost: Distribution, interrupt: Int, priority: Int) extends Simulation","d":"com/workflowfm/proter/SingleTaskSimulation","k":"class"},
{"l":"com/workflowfm/proter/SingleTaskSimulation.html","n":"name","t":"val name: String","d":"com/workflowfm/proter/SingleTaskSimulation","k":"val"},
{"l":"com/workflowfm/proter/SingleTaskSimulation.html","n":"theTask","t":"val theTask: Task","d":"com/workflowfm/proter/SingleTaskSimulation","k":"val"},
{"l":"com/workflowfm/proter/SingleTaskSimulationGenerator.html","n":"SingleTaskSimulationGenerator","t":"class SingleTaskSimulationGenerator(baseName: String, resources: Seq[String], duration: Distribution, cost: Distribution, interrupt: Int, priority: Int) extends SimulationGenerator","d":"com/workflowfm/proter/SingleTaskSimulationGenerator","k":"class"},
{"l":"com/workflowfm/proter/StartingSim.html","n":"StartingSim","t":"class StartingSim(time: Long, simulation: SimulationRef) extends DiscreteEvent","d":"com/workflowfm/proter/StartingSim","k":"class"},
{"l":"com/workflowfm/proter/StartingSim.html","n":"classOrder","t":"val classOrder: Short","d":"com/workflowfm/proter/StartingSim","k":"val"},
{"l":"com/workflowfm/proter/Task.html","n":"Task","t":"class Task(name: String, id: Option[UUID], duration: LongDistribution, cost: Distribution, minStartTime: Long, resources: Seq[String], interrupt: Int, priority: Int, createTime: Long)","d":"com/workflowfm/proter/Task","k":"class"},
{"l":"com/workflowfm/proter/Task.html","n":"create","t":"def create(simulation: String, currentTime: Long): TaskInstance","d":"com/workflowfm/proter/Task","k":"def"},
{"l":"com/workflowfm/proter/Task.html","n":"withCost","t":"def withCost(cost: Distribution): Task","d":"com/workflowfm/proter/Task","k":"def"},
{"l":"com/workflowfm/proter/Task.html","n":"withCost","t":"def withCost(cost: Double): Task","d":"com/workflowfm/proter/Task","k":"def"},
{"l":"com/workflowfm/proter/Task.html","n":"withCreationTime","t":"def withCreationTime(t: Long): Task","d":"com/workflowfm/proter/Task","k":"def"},
{"l":"com/workflowfm/proter/Task.html","n":"withDuration","t":"def withDuration(dur: LongDistribution): Task","d":"com/workflowfm/proter/Task","k":"def"},
{"l":"com/workflowfm/proter/Task.html","n":"withDuration","t":"def withDuration(dur: Long): Task","d":"com/workflowfm/proter/Task","k":"def"},
{"l":"com/workflowfm/proter/Task.html","n":"withID","t":"def withID(i: UUID): Task","d":"com/workflowfm/proter/Task","k":"def"},
{"l":"com/workflowfm/proter/Task.html","n":"withInterrupt","t":"def withInterrupt(int: Int): Task","d":"com/workflowfm/proter/Task","k":"def"},
{"l":"com/workflowfm/proter/Task.html","n":"withMinStartTime","t":"def withMinStartTime(t: Long): Task","d":"com/workflowfm/proter/Task","k":"def"},
{"l":"com/workflowfm/proter/Task.html","n":"withName","t":"def withName(n: String): Task","d":"com/workflowfm/proter/Task","k":"def"},
{"l":"com/workflowfm/proter/Task.html","n":"withPriority","t":"def withPriority(p: Int): Task","d":"com/workflowfm/proter/Task","k":"def"},
{"l":"com/workflowfm/proter/Task.html","n":"withResources","t":"def withResources(r: Seq[String]): Task","d":"com/workflowfm/proter/Task","k":"def"},
{"l":"com/workflowfm/proter/Task$.html","n":"Task","t":"object Task","d":"com/workflowfm/proter/Task$","k":"object"},
{"l":"com/workflowfm/proter/Task$.html","n":"High","t":"val High: Int","d":"com/workflowfm/proter/Task$","k":"val"},
{"l":"com/workflowfm/proter/Task$.html","n":"Highest","t":"val Highest: Int","d":"com/workflowfm/proter/Task$","k":"val"},
{"l":"com/workflowfm/proter/Task$.html","n":"Low","t":"val Low: Int","d":"com/workflowfm/proter/Task$","k":"val"},
{"l":"com/workflowfm/proter/Task$.html","n":"Medium","t":"val Medium: Int","d":"com/workflowfm/proter/Task$","k":"val"},
{"l":"com/workflowfm/proter/Task$.html","n":"VeryLow","t":"val VeryLow: Int","d":"com/workflowfm/proter/Task$","k":"val"},
{"l":"com/workflowfm/proter/Task$.html","n":"apply","t":"def apply(name: String, duration: LongDistribution): Task","d":"com/workflowfm/proter/Task$","k":"def"},
{"l":"com/workflowfm/proter/Task$.html","n":"apply","t":"def apply(name: String, duration: Long): Task","d":"com/workflowfm/proter/Task$","k":"def"},
{"l":"com/workflowfm/proter/Task$.html","n":"apply","t":"def apply(name: String, id: UUID, duration: Long): Task","d":"com/workflowfm/proter/Task$","k":"def"},
{"l":"com/workflowfm/proter/TaskInstance.html","n":"TaskInstance","t":"class TaskInstance(val id: UUID, val name: String, val simulation: String, val created: Long, val minStartTime: Long, val resources: Seq[String], val duration: Long, val estimatedDuration: Long, val cost: Double, val interrupt: Int, val priority: Int) extends Ordered[TaskInstance]","d":"com/workflowfm/proter/TaskInstance","k":"class"},
{"l":"com/workflowfm/proter/TaskInstance.html","n":"compare","t":"def compare(that: TaskInstance): Int","d":"com/workflowfm/proter/TaskInstance","k":"def"},
{"l":"com/workflowfm/proter/TaskInstance.html","n":"cost","t":"val cost: Double","d":"com/workflowfm/proter/TaskInstance","k":"val"},
{"l":"com/workflowfm/proter/TaskInstance.html","n":"created","t":"val created: Long","d":"com/workflowfm/proter/TaskInstance","k":"val"},
{"l":"com/workflowfm/proter/TaskInstance.html","n":"duration","t":"val duration: Long","d":"com/workflowfm/proter/TaskInstance","k":"val"},
{"l":"com/workflowfm/proter/TaskInstance.html","n":"estimatedDuration","t":"val estimatedDuration: Long","d":"com/workflowfm/proter/TaskInstance","k":"val"},
{"l":"com/workflowfm/proter/TaskInstance.html","n":"id","t":"val id: UUID","d":"com/workflowfm/proter/TaskInstance","k":"val"},
{"l":"com/workflowfm/proter/TaskInstance.html","n":"interrupt","t":"val interrupt: Int","d":"com/workflowfm/proter/TaskInstance","k":"val"},
{"l":"com/workflowfm/proter/TaskInstance.html","n":"minStartTime","t":"val minStartTime: Long","d":"com/workflowfm/proter/TaskInstance","k":"val"},
{"l":"com/workflowfm/proter/TaskInstance.html","n":"name","t":"val name: String","d":"com/workflowfm/proter/TaskInstance","k":"val"},
{"l":"com/workflowfm/proter/TaskInstance.html","n":"nextPossibleStart","t":"def nextPossibleStart(currentTime: Long, resourceMap: Map[String, TaskResource]): Long","d":"com/workflowfm/proter/TaskInstance","k":"def"},
{"l":"com/workflowfm/proter/TaskInstance.html","n":"priority","t":"val priority: Int","d":"com/workflowfm/proter/TaskInstance","k":"val"},
{"l":"com/workflowfm/proter/TaskInstance.html","n":"resources","t":"val resources: Seq[String]","d":"com/workflowfm/proter/TaskInstance","k":"val"},
{"l":"com/workflowfm/proter/TaskInstance.html","n":"simulation","t":"val simulation: String","d":"com/workflowfm/proter/TaskInstance","k":"val"},
{"l":"com/workflowfm/proter/TaskInstance.html","n":"taskResources","t":"def taskResources(resourceMap: Map[String, TaskResource]): Seq[TaskResource]","d":"com/workflowfm/proter/TaskInstance","k":"def"},
{"l":"com/workflowfm/proter/TaskResource.html","n":"TaskResource","t":"class TaskResource(val name: String, val costPerTick: Double)","d":"com/workflowfm/proter/TaskResource","k":"class"},
{"l":"com/workflowfm/proter/TaskResource.html","n":"abortSimulation","t":"def abortSimulation(simulation: String): Option[(Long, TaskInstance)]","d":"com/workflowfm/proter/TaskResource","k":"def"},
{"l":"com/workflowfm/proter/TaskResource.html","n":"abortTask","t":"def abortTask(id: UUID): Option[(Long, TaskInstance)]","d":"com/workflowfm/proter/TaskResource","k":"def"},
{"l":"com/workflowfm/proter/TaskResource.html","n":"costPerTick","t":"val costPerTick: Double","d":"com/workflowfm/proter/TaskResource","k":"val"},
{"l":"com/workflowfm/proter/TaskResource.html","n":"currentTask","t":"var currentTask: Option[(Long, TaskInstance)]","d":"com/workflowfm/proter/TaskResource","k":"var"},
{"l":"com/workflowfm/proter/TaskResource.html","n":"finishTask","t":"def finishTask(currentTime: Long): Option[TaskInstance]","d":"com/workflowfm/proter/TaskResource","k":"def"},
{"l":"com/workflowfm/proter/TaskResource.html","n":"isIdle","t":"def isIdle: Boolean","d":"com/workflowfm/proter/TaskResource","k":"def"},
{"l":"com/workflowfm/proter/TaskResource.html","n":"name","t":"val name: String","d":"com/workflowfm/proter/TaskResource","k":"val"},
{"l":"com/workflowfm/proter/TaskResource.html","n":"nextAvailableTimestamp","t":"def nextAvailableTimestamp(currentTime: Long): Long","d":"com/workflowfm/proter/TaskResource","k":"def"},
{"l":"com/workflowfm/proter/TaskResource.html","n":"startTask","t":"def startTask(task: TaskInstance, currentTime: Long): Option[TaskInstance]","d":"com/workflowfm/proter/TaskResource","k":"def"},
{"l":"com/workflowfm/proter/TimeLimit.html","n":"TimeLimit","t":"class TimeLimit(time: Long) extends DiscreteEvent","d":"com/workflowfm/proter/TimeLimit","k":"class"},
{"l":"com/workflowfm/proter/TimeLimit.html","n":"classOrder","t":"val classOrder: Short","d":"com/workflowfm/proter/TimeLimit","k":"val"},
{"l":"com/workflowfm/proter/Uniform.html","n":"Uniform","t":"class Uniform(min: Double, max: Double) extends Distribution","d":"com/workflowfm/proter/Uniform","k":"class"},
{"l":"com/workflowfm/proter/UniformLong.html","n":"UniformLong","t":"class UniformLong(min: Long, max: Long) extends LongDistribution","d":"com/workflowfm/proter/UniformLong","k":"class"},
{"l":"com/workflowfm/proter/akka.html","n":"com.workflowfm.proter.akka","t":"package com.workflowfm.proter.akka","d":"com/workflowfm/proter/akka","k":"package"},
{"l":"com/workflowfm/proter/akka/AkkaManager.html","n":"AkkaManager","t":"class AkkaManager(manager: ActorRef, timeout: Timeout) extends Manager","d":"com/workflowfm/proter/akka/AkkaManager","k":"class"},
{"l":"com/workflowfm/proter/akka/AkkaManager.html","n":"addArrival","t":"def addArrival(t: Long, limit: Int, rate: Distribution, simulationGenerator: SimulationRefGenerator): Unit","d":"com/workflowfm/proter/akka/AkkaManager","k":"def"},
{"l":"com/workflowfm/proter/akka/AkkaManager.html","n":"addArrivalNext","t":"def addArrivalNext(limit: Int, rate: Distribution, simulationGenerator: SimulationRefGenerator): Unit","d":"com/workflowfm/proter/akka/AkkaManager","k":"def"},
{"l":"com/workflowfm/proter/akka/AkkaManager.html","n":"addArrivalNow","t":"def addArrivalNow(limit: Int, rate: Distribution, simulationGenerator: SimulationRefGenerator): Unit","d":"com/workflowfm/proter/akka/AkkaManager","k":"def"},
{"l":"com/workflowfm/proter/akka/AkkaManager.html","n":"addInfiniteArrival","t":"def addInfiniteArrival(t: Long, rate: Distribution, simulationGenerator: SimulationRefGenerator): Unit","d":"com/workflowfm/proter/akka/AkkaManager","k":"def"},
{"l":"com/workflowfm/proter/akka/AkkaManager.html","n":"addInfiniteArrivalNext","t":"def addInfiniteArrivalNext(rate: Distribution, simulationGenerator: SimulationRefGenerator): Unit","d":"com/workflowfm/proter/akka/AkkaManager","k":"def"},
{"l":"com/workflowfm/proter/akka/AkkaManager.html","n":"addInfiniteArrivalNow","t":"def addInfiniteArrivalNow(rate: Distribution, simulationGenerator: SimulationRefGenerator): Unit","d":"com/workflowfm/proter/akka/AkkaManager","k":"def"},
{"l":"com/workflowfm/proter/akka/AkkaManager.html","n":"addResource","t":"def addResource(r: TaskResource): Unit","d":"com/workflowfm/proter/akka/AkkaManager","k":"def"},
{"l":"com/workflowfm/proter/akka/AkkaManager.html","n":"addResources","t":"def addResources(r: TaskResource*): Unit","d":"com/workflowfm/proter/akka/AkkaManager","k":"def"},
{"l":"com/workflowfm/proter/akka/AkkaManager.html","n":"addSimulation","t":"def addSimulation(t: Long, simulation: SimulationRef): Unit","d":"com/workflowfm/proter/akka/AkkaManager","k":"def"},
{"l":"com/workflowfm/proter/akka/AkkaManager.html","n":"addSimulationNow","t":"def addSimulationNow(simulation: SimulationRef): Unit","d":"com/workflowfm/proter/akka/AkkaManager","k":"def"},
{"l":"com/workflowfm/proter/akka/AkkaManager.html","n":"addSimulations","t":"def addSimulations(sims: Seq[(Long, SimulationRef)]): Unit","d":"com/workflowfm/proter/akka/AkkaManager","k":"def"},
{"l":"com/workflowfm/proter/akka/AkkaManager.html","n":"addSimulationsNow","t":"def addSimulationsNow(sims: SimulationRef*): Unit","d":"com/workflowfm/proter/akka/AkkaManager","k":"def"},
{"l":"com/workflowfm/proter/akka/AkkaManager.html","n":"limit","t":"def limit(t: Long): Unit","d":"com/workflowfm/proter/akka/AkkaManager","k":"def"},
{"l":"com/workflowfm/proter/akka/AkkaManager.html","n":"ping","t":"def ping(): Future[Time]","d":"com/workflowfm/proter/akka/AkkaManager","k":"def"},
{"l":"com/workflowfm/proter/akka/AkkaManager.html","n":"start","t":"def start(): Future[Any]","d":"com/workflowfm/proter/akka/AkkaManager","k":"def"},
{"l":"com/workflowfm/proter/akka/AkkaManager.html","n":"stop","t":"def stop(): Unit","d":"com/workflowfm/proter/akka/AkkaManager","k":"def"},
{"l":"com/workflowfm/proter/akka/AkkaManager$.html","n":"AkkaManager","t":"object AkkaManager","d":"com/workflowfm/proter/akka/AkkaManager$","k":"object"},
{"l":"com/workflowfm/proter/akka/AkkaManager$.html","n":"build","t":"def build(scheduler: Scheduler, startingTime: Long, timeout: Timeout)(using system: ActorSystem): AkkaManager","d":"com/workflowfm/proter/akka/AkkaManager$","k":"def"},
{"l":"com/workflowfm/proter/akka/AkkaSimulationGenerator.html","n":"AkkaSimulationGenerator","t":"class AkkaSimulationGenerator(gen: SimulationGenerator)(using system: ActorSystem) extends SimulationRefGenerator","d":"com/workflowfm/proter/akka/AkkaSimulationGenerator","k":"class"},
{"l":"com/workflowfm/proter/akka/AkkaSimulationGenerator$.html","n":"AkkaSimulationGenerator","t":"object AkkaSimulationGenerator","d":"com/workflowfm/proter/akka/AkkaSimulationGenerator$","k":"object"},
{"l":"com/workflowfm/proter/akka/AkkaSimulationGenerator$.html","n":"of","t":"def of(gen: SimulationRefGenerator)(using system: ActorSystem): SimulationRefGenerator","d":"com/workflowfm/proter/akka/AkkaSimulationGenerator$","k":"def"},
{"l":"com/workflowfm/proter/akka/AkkaSimulationRef.html","n":"AkkaSimulationRef","t":"class AkkaSimulationRef(simName: String, simulation: ActorRef) extends SimulationRef","d":"com/workflowfm/proter/akka/AkkaSimulationRef","k":"class"},
{"l":"com/workflowfm/proter/akka/AkkaSimulationRef$.html","n":"AkkaSimulationRef","t":"object AkkaSimulationRef","d":"com/workflowfm/proter/akka/AkkaSimulationRef$","k":"object"},
{"l":"com/workflowfm/proter/akka/AkkaSimulationRef$.html","n":"of","t":"def of(simulation: Simulation)(using system: ActorSystem): SimulationRef","d":"com/workflowfm/proter/akka/AkkaSimulationRef$","k":"def"},
{"l":"com/workflowfm/proter/akka/AkkaSimulationRef$.html","n":"ofRef","t":"def ofRef(simulationRef: SimulationRef)(using system: ActorSystem): SimulationRef","d":"com/workflowfm/proter/akka/AkkaSimulationRef$","k":"def"},
{"l":"com/workflowfm/proter/akka/CoordinatorActor.html","n":"CoordinatorActor","t":"class CoordinatorActor(scheduler: Scheduler, startingTime: Long)(using actorSystem: ActorSystem) extends Actor","d":"com/workflowfm/proter/akka/CoordinatorActor","k":"class"},
{"l":"com/workflowfm/proter/akka/CoordinatorActor.html","n":"ExecutionContext","t":"val ExecutionContext: ExecutionContext","d":"com/workflowfm/proter/akka/CoordinatorActor","k":"val"},
{"l":"com/workflowfm/proter/akka/CoordinatorActor.html","n":"coordinator","t":"val coordinator: Coordinator","d":"com/workflowfm/proter/akka/CoordinatorActor","k":"val"},
{"l":"com/workflowfm/proter/akka/CoordinatorActor.html","n":"receive","t":"def receive: Receive","d":"com/workflowfm/proter/akka/CoordinatorActor","k":"def"},
{"l":"com/workflowfm/proter/akka/SimulationActor.html","n":"SimulationActor","t":"class SimulationActor(val simulation: Simulation) extends SimulationRefActor with Actor","d":"com/workflowfm/proter/akka/SimulationActor","k":"class"},
{"l":"com/workflowfm/proter/akka/SimulationActor.html","n":"simulation","t":"val simulation: Simulation","d":"com/workflowfm/proter/akka/SimulationActor","k":"val"},
{"l":"com/workflowfm/proter/akka/SimulationActor.html","n":"simulationReceive","t":"def simulationReceive: Receive","d":"com/workflowfm/proter/akka/SimulationActor","k":"def"},
{"l":"com/workflowfm/proter/akka/SimulationActor$.html","n":"SimulationActor","t":"object SimulationActor","d":"com/workflowfm/proter/akka/SimulationActor$","k":"object"},
{"l":"com/workflowfm/proter/akka/SimulationActor$$AbortTasks.html","n":"AbortTasks","t":"class AbortTasks(ids: Seq[UUID])","d":"com/workflowfm/proter/akka/SimulationActor$$AbortTasks","k":"class"},
{"l":"com/workflowfm/proter/akka/SimulationActor$$AckTasks.html","n":"AckTasks","t":"class AckTasks(tasks: Seq[UUID])","d":"com/workflowfm/proter/akka/SimulationActor$$AckTasks","k":"class"},
{"l":"com/workflowfm/proter/akka/SimulationActor$$AddTasks.html","n":"AddTasks","t":"class AddTasks(tasks: Seq[Task])","d":"com/workflowfm/proter/akka/SimulationActor$$AddTasks","k":"class"},
{"l":"com/workflowfm/proter/akka/SimulationActor$$Done.html","n":"Done","t":"class Done(result: Try[Any])","d":"com/workflowfm/proter/akka/SimulationActor$$Done","k":"class"},
{"l":"com/workflowfm/proter/akka/SimulationActor$$Fail.html","n":"Fail","t":"class Fail(exception: Throwable)","d":"com/workflowfm/proter/akka/SimulationActor$$Fail","k":"class"},
{"l":"com/workflowfm/proter/akka/SimulationActor$$Ready$.html","n":"Ready","t":"object Ready","d":"com/workflowfm/proter/akka/SimulationActor$$Ready$","k":"object"},
{"l":"com/workflowfm/proter/akka/SimulationActor$$Succeed.html","n":"Succeed","t":"class Succeed(result: Any)","d":"com/workflowfm/proter/akka/SimulationActor$$Succeed","k":"class"},
{"l":"com/workflowfm/proter/akka/SimulationActor$$Wait$.html","n":"Wait","t":"object Wait","d":"com/workflowfm/proter/akka/SimulationActor$$Wait$","k":"object"},
{"l":"com/workflowfm/proter/akka/SimulationRefActor.html","n":"SimulationRefActor","t":"class SimulationRefActor(val simulationRef: SimulationRef) extends Actor","d":"com/workflowfm/proter/akka/SimulationRefActor","k":"class"},
{"l":"com/workflowfm/proter/akka/SimulationRefActor.html","n":"receive","t":"def receive: Receive","d":"com/workflowfm/proter/akka/SimulationRefActor","k":"def"},
{"l":"com/workflowfm/proter/akka/SimulationRefActor.html","n":"simulationRef","t":"val simulationRef: SimulationRef","d":"com/workflowfm/proter/akka/SimulationRefActor","k":"val"},
{"l":"com/workflowfm/proter/akka/SimulationRefActor.html","n":"simulationRefReceive","t":"def simulationRefReceive: Receive","d":"com/workflowfm/proter/akka/SimulationRefActor","k":"def"},
{"l":"com/workflowfm/proter/akka/SimulationRefActor$.html","n":"SimulationRefActor","t":"object SimulationRefActor","d":"com/workflowfm/proter/akka/SimulationRefActor$","k":"object"},
{"l":"com/workflowfm/proter/akka/SimulationRefActor$$Completed.html","n":"Completed","t":"class Completed(time: Long, tasks: Seq[TaskInstance])","d":"com/workflowfm/proter/akka/SimulationRefActor$$Completed","k":"class"},
{"l":"com/workflowfm/proter/akka/SimulationRefActor$$Run$.html","n":"Run","t":"object Run","d":"com/workflowfm/proter/akka/SimulationRefActor$$Run$","k":"object"},
{"l":"com/workflowfm/proter/akka/SimulationRefActor$$Stop$.html","n":"Stop","t":"object Stop","d":"com/workflowfm/proter/akka/SimulationRefActor$$Stop$","k":"object"},
{"l":"com/workflowfm/proter/events.html","n":"com.workflowfm.proter.events","t":"package com.workflowfm.proter.events","d":"com/workflowfm/proter/events","k":"package"},
{"l":"com/workflowfm/proter/events/CounterHandler.html","n":"CounterHandler","t":"class CounterHandler extends ResultHandler[Int]","d":"com/workflowfm/proter/events/CounterHandler","k":"class"},
{"l":"com/workflowfm/proter/events/CounterHandler.html","n":"count","t":"var count: Int","d":"com/workflowfm/proter/events/CounterHandler","k":"var"},
{"l":"com/workflowfm/proter/events/EDone.html","n":"EDone","t":"class EDone(source: String, time: Long) extends Event","d":"com/workflowfm/proter/events/EDone","k":"class"},
{"l":"com/workflowfm/proter/events/EError.html","n":"EError","t":"class EError(source: String, time: Long, error: String) extends Event","d":"com/workflowfm/proter/events/EError","k":"class"},
{"l":"com/workflowfm/proter/events/EResourceAdd.html","n":"EResourceAdd","t":"class EResourceAdd(source: String, time: Long, name: String, costPerTick: Double) extends Event","d":"com/workflowfm/proter/events/EResourceAdd","k":"class"},
{"l":"com/workflowfm/proter/events/ESimAdd.html","n":"ESimAdd","t":"class ESimAdd(source: String, time: Long, name: String, start: Long) extends Event","d":"com/workflowfm/proter/events/ESimAdd","k":"class"},
{"l":"com/workflowfm/proter/events/ESimEnd.html","n":"ESimEnd","t":"class ESimEnd(source: String, time: Long, name: String, result: String) extends Event","d":"com/workflowfm/proter/events/ESimEnd","k":"class"},
{"l":"com/workflowfm/proter/events/ESimStart.html","n":"ESimStart","t":"class ESimStart(source: String, time: Long, name: String) extends Event","d":"com/workflowfm/proter/events/ESimStart","k":"class"},
{"l":"com/workflowfm/proter/events/EStart.html","n":"EStart","t":"class EStart(source: String, time: Long) extends Event","d":"com/workflowfm/proter/events/EStart","k":"class"},
{"l":"com/workflowfm/proter/events/ETaskAbort.html","n":"ETaskAbort","t":"class ETaskAbort(source: String, time: Long, id: UUID) extends Event","d":"com/workflowfm/proter/events/ETaskAbort","k":"class"},
{"l":"com/workflowfm/proter/events/ETaskAdd.html","n":"ETaskAdd","t":"class ETaskAdd(source: String, time: Long, task: TaskInstance) extends Event","d":"com/workflowfm/proter/events/ETaskAdd","k":"class"},
{"l":"com/workflowfm/proter/events/ETaskAttach.html","n":"ETaskAttach","t":"class ETaskAttach(source: String, time: Long, task: TaskInstance, resource: String) extends Event","d":"com/workflowfm/proter/events/ETaskAttach","k":"class"},
{"l":"com/workflowfm/proter/events/ETaskDetach.html","n":"ETaskDetach","t":"class ETaskDetach(source: String, time: Long, task: TaskInstance, resource: String, cost: Double) extends Event","d":"com/workflowfm/proter/events/ETaskDetach","k":"class"},
{"l":"com/workflowfm/proter/events/ETaskDone.html","n":"ETaskDone","t":"class ETaskDone(source: String, time: Long, task: TaskInstance) extends Event","d":"com/workflowfm/proter/events/ETaskDone","k":"class"},
{"l":"com/workflowfm/proter/events/ETaskStart.html","n":"ETaskStart","t":"class ETaskStart(source: String, time: Long, task: TaskInstance) extends Event","d":"com/workflowfm/proter/events/ETaskStart","k":"class"},
{"l":"com/workflowfm/proter/events/Event.html","n":"Event","t":"trait Event","d":"com/workflowfm/proter/events/Event","k":"trait"},
{"l":"com/workflowfm/proter/events/Event.html","n":"source","t":"val source: String","d":"com/workflowfm/proter/events/Event","k":"val"},
{"l":"com/workflowfm/proter/events/Event.html","n":"time","t":"val time: Long","d":"com/workflowfm/proter/events/Event","k":"val"},
{"l":"com/workflowfm/proter/events/Event$.html","n":"Event","t":"object Event","d":"com/workflowfm/proter/events/Event$","k":"object"},
{"l":"com/workflowfm/proter/events/Event$.html","n":"asString","t":"def asString(e: Event): String","d":"com/workflowfm/proter/events/Event$","k":"def"},
{"l":"com/workflowfm/proter/events/EventHandler.html","n":"EventHandler","t":"trait EventHandler","d":"com/workflowfm/proter/events/EventHandler","k":"trait"},
{"l":"com/workflowfm/proter/events/EventHandler.html","n":"id","t":"val id: UUID","d":"com/workflowfm/proter/events/EventHandler","k":"val"},
{"l":"com/workflowfm/proter/events/EventHandler.html","n":"onDone","t":"def onDone(publisher: Publisher): Unit","d":"com/workflowfm/proter/events/EventHandler","k":"def"},
{"l":"com/workflowfm/proter/events/EventHandler.html","n":"onEvent","t":"def onEvent(event: Event): Unit","d":"com/workflowfm/proter/events/EventHandler","k":"def"},
{"l":"com/workflowfm/proter/events/EventHandler.html","n":"onFail","t":"def onFail(e: Throwable, publisher: Publisher): Unit","d":"com/workflowfm/proter/events/EventHandler","k":"def"},
{"l":"com/workflowfm/proter/events/EventHandler.html","n":"onInit","t":"def onInit(publisher: Publisher): Unit","d":"com/workflowfm/proter/events/EventHandler","k":"def"},
{"l":"com/workflowfm/proter/events/HashMapPublisher.html","n":"HashMapPublisher","t":"trait HashMapPublisher extends Publisher","d":"com/workflowfm/proter/events/HashMapPublisher","k":"trait"},
{"l":"com/workflowfm/proter/events/HashMapPublisher.html","n":"subscribers","t":"val subscribers: HashMap[UUID, EventHandler]","d":"com/workflowfm/proter/events/HashMapPublisher","k":"val"},
{"l":"com/workflowfm/proter/events/PoolEventHandler.html","n":"PoolEventHandler","t":"trait PoolEventHandler extends EventHandler","d":"com/workflowfm/proter/events/PoolEventHandler","k":"trait"},
{"l":"com/workflowfm/proter/events/PoolEventHandler.html","n":"publishers","t":"val publishers: HashSet[Publisher]","d":"com/workflowfm/proter/events/PoolEventHandler","k":"val"},
{"l":"com/workflowfm/proter/events/PrintEventHandler.html","n":"PrintEventHandler","t":"class PrintEventHandler extends EventHandler","d":"com/workflowfm/proter/events/PrintEventHandler","k":"class"},
{"l":"com/workflowfm/proter/events/PrintEventHandler.html","n":"formatter","t":"val formatter: SimpleDateFormat","d":"com/workflowfm/proter/events/PrintEventHandler","k":"val"},
{"l":"com/workflowfm/proter/events/PromiseHandler.html","n":"PromiseHandler","t":"class PromiseHandler[R](handler: ResultHandler[R]) extends ResultHandler[R]","d":"com/workflowfm/proter/events/PromiseHandler","k":"class"},
{"l":"com/workflowfm/proter/events/PromiseHandler.html","n":"future","t":"def future: Future[R]","d":"com/workflowfm/proter/events/PromiseHandler","k":"def"},
{"l":"com/workflowfm/proter/events/PromiseHandler$.html","n":"PromiseHandler","t":"object PromiseHandler","d":"com/workflowfm/proter/events/PromiseHandler$","k":"object"},
{"l":"com/workflowfm/proter/events/PromiseHandler$.html","n":"of","t":"def of[R](handler: ResultHandler[R]): PromiseHandler[R]","d":"com/workflowfm/proter/events/PromiseHandler$","k":"def"},
{"l":"com/workflowfm/proter/events/Publisher.html","n":"Publisher","t":"trait Publisher","d":"com/workflowfm/proter/events/Publisher","k":"trait"},
{"l":"com/workflowfm/proter/events/Publisher.html","n":"doPublish","t":"def doPublish(evt: Event): Unit","d":"com/workflowfm/proter/events/Publisher","k":"def"},
{"l":"com/workflowfm/proter/events/Publisher.html","n":"isFinalEvent","t":"def isFinalEvent(e: Event): Boolean","d":"com/workflowfm/proter/events/Publisher","k":"def"},
{"l":"com/workflowfm/proter/events/Publisher.html","n":"publish","t":"def publish(evt: Event): Unit","d":"com/workflowfm/proter/events/Publisher","k":"def"},
{"l":"com/workflowfm/proter/events/Publisher.html","n":"stopStream","t":"def stopStream(): Unit","d":"com/workflowfm/proter/events/Publisher","k":"def"},
{"l":"com/workflowfm/proter/events/Publisher.html","n":"subscribe","t":"def subscribe(subscriber: EventHandler): Unit","d":"com/workflowfm/proter/events/Publisher","k":"def"},
{"l":"com/workflowfm/proter/events/Publisher.html","n":"unsubscribe","t":"def unsubscribe(subscriber: EventHandler): Unit","d":"com/workflowfm/proter/events/Publisher","k":"def"},
{"l":"com/workflowfm/proter/events/ResultHandler.html","n":"ResultHandler","t":"trait ResultHandler[R] extends EventHandler","d":"com/workflowfm/proter/events/ResultHandler","k":"trait"},
{"l":"com/workflowfm/proter/events/ResultHandler.html","n":"result","t":"def result: R","d":"com/workflowfm/proter/events/ResultHandler","k":"def"},
{"l":"com/workflowfm/proter/events/SimulationResultHandler.html","n":"SimulationResultHandler","t":"class SimulationResultHandler(name: String, callback: String => Unit) extends ResultHandler[Option[String]]","d":"com/workflowfm/proter/events/SimulationResultHandler","k":"class"},
{"l":"com/workflowfm/proter/events/SimulationResultHandler.html","n":"publisher","t":"var publisher: Option[Publisher]","d":"com/workflowfm/proter/events/SimulationResultHandler","k":"var"},
{"l":"com/workflowfm/proter/events/SimulationResultHandler.html","n":"simResult","t":"var simResult: Option[String]","d":"com/workflowfm/proter/events/SimulationResultHandler","k":"var"},
{"l":"com/workflowfm/proter/flows.html","n":"com.workflowfm.proter.flows","t":"package com.workflowfm.proter.flows","d":"com/workflowfm/proter/flows","k":"package"},
{"l":"com/workflowfm/proter/flows/And.html","n":"And","t":"class And(val left: Flow, val right: Flow) extends Flow","d":"com/workflowfm/proter/flows/And","k":"class"},
{"l":"com/workflowfm/proter/flows/And.html","n":"left","t":"val left: Flow","d":"com/workflowfm/proter/flows/And","k":"val"},
{"l":"com/workflowfm/proter/flows/And.html","n":"right","t":"val right: Flow","d":"com/workflowfm/proter/flows/And","k":"val"},
{"l":"com/workflowfm/proter/flows/Flow.html","n":"Flow","t":"trait Flow","d":"com/workflowfm/proter/flows/Flow","k":"trait"},
{"l":"com/workflowfm/proter/flows/Flow.html","n":"*","t":"def *(i: Int): Flow","d":"com/workflowfm/proter/flows/Flow","k":"def"},
{"l":"com/workflowfm/proter/flows/Flow.html","n":"+","t":"def +(f: Flow): Flow","d":"com/workflowfm/proter/flows/Flow","k":"def"},
{"l":"com/workflowfm/proter/flows/Flow.html","n":"+","t":"def +(t: Task): Flow","d":"com/workflowfm/proter/flows/Flow","k":"def"},
{"l":"com/workflowfm/proter/flows/Flow.html","n":">","t":"def >(f: Flow): Flow","d":"com/workflowfm/proter/flows/Flow","k":"def"},
{"l":"com/workflowfm/proter/flows/Flow.html","n":">","t":"def >(t: Task): Flow","d":"com/workflowfm/proter/flows/Flow","k":"def"},
{"l":"com/workflowfm/proter/flows/Flow.html","n":"copy","t":"def copy(): Flow","d":"com/workflowfm/proter/flows/Flow","k":"def"},
{"l":"com/workflowfm/proter/flows/Flow.html","n":"id","t":"val id: UUID","d":"com/workflowfm/proter/flows/Flow","k":"val"},
{"l":"com/workflowfm/proter/flows/Flow.html","n":"simGenerator","t":"def simGenerator(name: String): FlowSimulationGenerator","d":"com/workflowfm/proter/flows/Flow","k":"def"},
{"l":"com/workflowfm/proter/flows/Flow.html","n":"simulation","t":"def simulation(name: String, manager: Manager): FlowSimulation","d":"com/workflowfm/proter/flows/Flow","k":"def"},
{"l":"com/workflowfm/proter/flows/Flow.html","n":"|","t":"def |(f: Flow): Flow","d":"com/workflowfm/proter/flows/Flow","k":"def"},
{"l":"com/workflowfm/proter/flows/Flow.html","n":"|","t":"def |(t: Task): Flow","d":"com/workflowfm/proter/flows/Flow","k":"def"},
{"l":"com/workflowfm/proter/flows/Flow$.html","n":"Flow","t":"object Flow","d":"com/workflowfm/proter/flows/Flow$","k":"object"},
{"l":"com/workflowfm/proter/flows/Flow$.html","n":"apply","t":"def apply(t: Task*): Flow","d":"com/workflowfm/proter/flows/Flow$","k":"def"},
{"l":"com/workflowfm/proter/flows/Flow$$given_Conversion_Task_FlowTask$.html","n":"given_Conversion_Task_FlowTask","t":"given given_Conversion_Task_FlowTask: Conversion[Task, FlowTask]","d":"com/workflowfm/proter/flows/Flow$","k":"given"},
{"l":"com/workflowfm/proter/flows/Flow$$given_Conversion_Task_FlowTask$.html","n":"apply","t":"def apply(t: Task): FlowTask","d":"com/workflowfm/proter/flows/Flow$","k":"def"},
{"l":"com/workflowfm/proter/flows/Flow$.html","n":"par","t":"def par(l: Seq[Flow]): Flow","d":"com/workflowfm/proter/flows/Flow$","k":"def"},
{"l":"com/workflowfm/proter/flows/Flow$.html","n":"seq","t":"def seq(l: Seq[Flow]): Flow","d":"com/workflowfm/proter/flows/Flow$","k":"def"},
{"l":"com/workflowfm/proter/flows/Flow$$given_Conversion_Task_FlowTask$.html","n":"given_Conversion_Task_FlowTask","t":"given given_Conversion_Task_FlowTask: Conversion[Task, FlowTask]","d":"com/workflowfm/proter/flows/Flow$$given_Conversion_Task_FlowTask$","k":"given"},
{"l":"com/workflowfm/proter/flows/Flow$$given_Conversion_Task_FlowTask$.html","n":"apply","t":"def apply(t: Task): FlowTask","d":"com/workflowfm/proter/flows/Flow$$given_Conversion_Task_FlowTask$","k":"def"},
{"l":"com/workflowfm/proter/flows/FlowLookahead.html","n":"FlowLookahead","t":"class FlowLookahead(name: String, manager: Manager, flow: Flow) extends FlowSimulation with LookingAhead","d":"com/workflowfm/proter/flows/FlowLookahead","k":"class"},
{"l":"com/workflowfm/proter/flows/FlowLookahead.html","n":"IDFunction","t":"type IDFunction = Map[UUID, Long] => Option[Long]","d":"com/workflowfm/proter/flows/FlowLookahead","k":"type"},
{"l":"com/workflowfm/proter/flows/FlowLookahead.html","n":"parseFlow","t":"def parseFlow(flow: Flow, extraFunction: Option[IDFunction], lookaheadStructure: Lookahead): (IDFunction, Lookahead)","d":"com/workflowfm/proter/flows/FlowLookahead","k":"def"},
{"l":"com/workflowfm/proter/flows/FlowSimulation.html","n":"FlowSimulation","t":"class FlowSimulation(val name: String, val manager: Manager, val flow: Flow) extends AsyncSimulation","d":"com/workflowfm/proter/flows/FlowSimulation","k":"class"},
{"l":"com/workflowfm/proter/flows/FlowSimulation.html","n":"name","t":"val name: String","d":"com/workflowfm/proter/flows/FlowSimulation","k":"val"},
{"l":"com/workflowfm/proter/flows/FlowSimulationGenerator.html","n":"FlowSimulationGenerator","t":"class FlowSimulationGenerator(baseName: String, flow: Flow) extends SimulationGenerator","d":"com/workflowfm/proter/flows/FlowSimulationGenerator","k":"class"},
{"l":"com/workflowfm/proter/flows/FlowTask.html","n":"FlowTask","t":"class FlowTask(t: Task) extends Flow","d":"com/workflowfm/proter/flows/FlowTask","k":"class"},
{"l":"com/workflowfm/proter/flows/FlowTask.html","n":"id","t":"val id: UUID","d":"com/workflowfm/proter/flows/FlowTask","k":"val"},
{"l":"com/workflowfm/proter/flows/FlowTask.html","n":"task","t":"val task: Task","d":"com/workflowfm/proter/flows/FlowTask","k":"val"},
{"l":"com/workflowfm/proter/flows/NoTask.html","n":"NoTask","t":"class NoTask() extends Flow","d":"com/workflowfm/proter/flows/NoTask","k":"class"},
{"l":"com/workflowfm/proter/flows/Or.html","n":"Or","t":"class Or(val left: Flow, val right: Flow) extends Flow","d":"com/workflowfm/proter/flows/Or","k":"class"},
{"l":"com/workflowfm/proter/flows/Or.html","n":"left","t":"val left: Flow","d":"com/workflowfm/proter/flows/Or","k":"val"},
{"l":"com/workflowfm/proter/flows/Or.html","n":"right","t":"val right: Flow","d":"com/workflowfm/proter/flows/Or","k":"val"},
{"l":"com/workflowfm/proter/flows/RandomFlowFactory.html","n":"RandomFlowFactory","t":"class RandomFlowFactory(andProbability: Float, resources: Seq[TaskResource], numTasks: Distribution, durations: LongDistribution, numResources: Distribution, cost: Distribution, priority: Distribution)","d":"com/workflowfm/proter/flows/RandomFlowFactory","k":"class"},
{"l":"com/workflowfm/proter/flows/RandomFlowFactory.html","n":"build","t":"def build(): Flow","d":"com/workflowfm/proter/flows/RandomFlowFactory","k":"def"},
{"l":"com/workflowfm/proter/flows/RandomFlowFactory.html","n":"withDurations","t":"def withDurations(d: LongDistribution): RandomFlowFactory","d":"com/workflowfm/proter/flows/RandomFlowFactory","k":"def"},
{"l":"com/workflowfm/proter/flows/RandomFlowFactory.html","n":"withNumResources","t":"def withNumResources(d: Distribution): RandomFlowFactory","d":"com/workflowfm/proter/flows/RandomFlowFactory","k":"def"},
{"l":"com/workflowfm/proter/flows/RandomFlowFactory.html","n":"withRandomPriority","t":"def withRandomPriority(d: Distribution): RandomFlowFactory","d":"com/workflowfm/proter/flows/RandomFlowFactory","k":"def"},
{"l":"com/workflowfm/proter/flows/RandomFlowFactory.html","n":"withResources","t":"def withResources(r: Seq[TaskResource]): RandomFlowFactory","d":"com/workflowfm/proter/flows/RandomFlowFactory","k":"def"},
{"l":"com/workflowfm/proter/flows/RandomFlowFactory.html","n":"withTasks","t":"def withTasks(d: Distribution): RandomFlowFactory","d":"com/workflowfm/proter/flows/RandomFlowFactory","k":"def"},
{"l":"com/workflowfm/proter/flows/Then.html","n":"Then","t":"class Then(val left: Flow, val right: Flow) extends Flow","d":"com/workflowfm/proter/flows/Then","k":"class"},
{"l":"com/workflowfm/proter/flows/Then.html","n":"left","t":"val left: Flow","d":"com/workflowfm/proter/flows/Then","k":"val"},
{"l":"com/workflowfm/proter/flows/Then.html","n":"right","t":"val right: Flow","d":"com/workflowfm/proter/flows/Then","k":"val"},
{"l":"com/workflowfm/proter/metrics.html","n":"com.workflowfm.proter.metrics","t":"package com.workflowfm.proter.metrics","d":"com/workflowfm/proter/metrics","k":"package"},
{"l":"com/workflowfm/proter/metrics/FileOutput.html","n":"FileOutput","t":"trait FileOutput","d":"com/workflowfm/proter/metrics/FileOutput","k":"trait"},
{"l":"com/workflowfm/proter/metrics/FileOutput.html","n":"writeToFile","t":"def writeToFile(filePath: String, output: String): Unit","d":"com/workflowfm/proter/metrics/FileOutput","k":"def"},
{"l":"com/workflowfm/proter/metrics/ResourceMetrics.html","n":"ResourceMetrics","t":"class ResourceMetrics(name: String, costPerTick: Double, idleUpdate: Long, busyTime: Long, idleTime: Long, tasks: Int, cost: Double)","d":"com/workflowfm/proter/metrics/ResourceMetrics","k":"class"},
{"l":"com/workflowfm/proter/metrics/ResourceMetrics.html","n":"idle","t":"def idle(t: Long): ResourceMetrics","d":"com/workflowfm/proter/metrics/ResourceMetrics","k":"def"},
{"l":"com/workflowfm/proter/metrics/ResourceMetrics.html","n":"task","t":"def task(t: Long, task: TaskInstance): ResourceMetrics","d":"com/workflowfm/proter/metrics/ResourceMetrics","k":"def"},
{"l":"com/workflowfm/proter/metrics/ResourceMetrics$.html","n":"ResourceMetrics","t":"object ResourceMetrics","d":"com/workflowfm/proter/metrics/ResourceMetrics$","k":"object"},
{"l":"com/workflowfm/proter/metrics/ResourceMetrics$.html","n":"apply","t":"def apply(name: String, costPerTick: Double): ResourceMetrics","d":"com/workflowfm/proter/metrics/ResourceMetrics$","k":"def"},
{"l":"com/workflowfm/proter/metrics/SimCSVFileOutput.html","n":"SimCSVFileOutput","t":"class SimCSVFileOutput(path: String, name: String) extends SimMetricsStringOutput with FileOutput","d":"com/workflowfm/proter/metrics/SimCSVFileOutput","k":"class"},
{"l":"com/workflowfm/proter/metrics/SimCSVFileOutput.html","n":"apply","t":"def apply(totalTicks: Long, aggregator: SimMetricsAggregator): Unit","d":"com/workflowfm/proter/metrics/SimCSVFileOutput","k":"def"},
{"l":"com/workflowfm/proter/metrics/SimCSVFileOutput.html","n":"lineSep","t":"val lineSep: String","d":"com/workflowfm/proter/metrics/SimCSVFileOutput","k":"val"},
{"l":"com/workflowfm/proter/metrics/SimCSVFileOutput.html","n":"separator","t":"val separator: String","d":"com/workflowfm/proter/metrics/SimCSVFileOutput","k":"val"},
{"l":"com/workflowfm/proter/metrics/SimD3Timeline.html","n":"SimD3Timeline","t":"class SimD3Timeline(path: String, file: String, tick: Int) extends SimMetricsOutput with FileOutput","d":"com/workflowfm/proter/metrics/SimD3Timeline","k":"class"},
{"l":"com/workflowfm/proter/metrics/SimD3Timeline.html","n":"build","t":"def build(aggregator: SimMetricsAggregator, now: Long): String","d":"com/workflowfm/proter/metrics/SimD3Timeline","k":"def"},
{"l":"com/workflowfm/proter/metrics/SimD3Timeline.html","n":"resourceEntry","t":"def resourceEntry(res: ResourceMetrics, agg: SimMetricsAggregator): String","d":"com/workflowfm/proter/metrics/SimD3Timeline","k":"def"},
{"l":"com/workflowfm/proter/metrics/SimD3Timeline.html","n":"simulationEntry","t":"def simulationEntry(s: SimulationMetrics, agg: SimMetricsAggregator): String","d":"com/workflowfm/proter/metrics/SimD3Timeline","k":"def"},
{"l":"com/workflowfm/proter/metrics/SimD3Timeline.html","n":"taskEntry","t":"def taskEntry(m: TaskMetrics): Option[String]","d":"com/workflowfm/proter/metrics/SimD3Timeline","k":"def"},
{"l":"com/workflowfm/proter/metrics/SimMetricsHandler.html","n":"SimMetricsHandler","t":"class SimMetricsHandler(output: SimMetricsOutput) extends ResultHandler[SimMetricsAggregator]","d":"com/workflowfm/proter/metrics/SimMetricsHandler","k":"class"},
{"l":"com/workflowfm/proter/metrics/SimMetricsHandler.html","n":"metrics","t":"val metrics: SimMetricsAggregator","d":"com/workflowfm/proter/metrics/SimMetricsHandler","k":"val"},
{"l":"com/workflowfm/proter/metrics/SimMetricsOutput.html","n":"SimMetricsOutput","t":"trait SimMetricsOutput extends (Long, SimMetricsAggregator) => Unit","d":"com/workflowfm/proter/metrics/SimMetricsOutput","k":"trait"},
{"l":"com/workflowfm/proter/metrics/SimMetricsOutput.html","n":"and","t":"def and(h: SimMetricsOutput): SimMetricsOutputs","d":"com/workflowfm/proter/metrics/SimMetricsOutput","k":"def"},
{"l":"com/workflowfm/proter/metrics/SimMetricsOutput$.html","n":"SimMetricsOutput","t":"object SimMetricsOutput","d":"com/workflowfm/proter/metrics/SimMetricsOutput$","k":"object"},
{"l":"com/workflowfm/proter/metrics/SimMetricsOutput$.html","n":"formatDuration","t":"def formatDuration(from: Long, to: Long, format: String): String","d":"com/workflowfm/proter/metrics/SimMetricsOutput$","k":"def"},
{"l":"com/workflowfm/proter/metrics/SimMetricsOutput$.html","n":"formatDuration","t":"def formatDuration(from: Option[Long], to: Long, format: String, nullValue: String): String","d":"com/workflowfm/proter/metrics/SimMetricsOutput$","k":"def"},
{"l":"com/workflowfm/proter/metrics/SimMetricsOutput$.html","n":"formatDuration","t":"def formatDuration(from: Option[Long], to: Option[Long], format: String, nullValue: String): String","d":"com/workflowfm/proter/metrics/SimMetricsOutput$","k":"def"},
{"l":"com/workflowfm/proter/metrics/SimMetricsOutput$.html","n":"formatOption","t":"def formatOption[T](v: Option[T], nullValue: String, format: T => String): String","d":"com/workflowfm/proter/metrics/SimMetricsOutput$","k":"def"},
{"l":"com/workflowfm/proter/metrics/SimMetricsOutput$.html","n":"formatTime","t":"def formatTime(format: String)(time: Long): String","d":"com/workflowfm/proter/metrics/SimMetricsOutput$","k":"def"},
{"l":"com/workflowfm/proter/metrics/SimMetricsOutput$.html","n":"formatTimeOption","t":"def formatTimeOption(time: Option[Long], format: String, nullValue: String): String","d":"com/workflowfm/proter/metrics/SimMetricsOutput$","k":"def"},
{"l":"com/workflowfm/proter/metrics/SimMetricsOutputs.html","n":"SimMetricsOutputs","t":"class SimMetricsOutputs(handlers: Queue[SimMetricsOutput]) extends SimMetricsOutput","d":"com/workflowfm/proter/metrics/SimMetricsOutputs","k":"class"},
{"l":"com/workflowfm/proter/metrics/SimMetricsOutputs$.html","n":"SimMetricsOutputs","t":"object SimMetricsOutputs","d":"com/workflowfm/proter/metrics/SimMetricsOutputs$","k":"object"},
{"l":"com/workflowfm/proter/metrics/SimMetricsOutputs$.html","n":"apply","t":"def apply(handlers: SimMetricsOutput*): SimMetricsOutputs","d":"com/workflowfm/proter/metrics/SimMetricsOutputs$","k":"def"},
{"l":"com/workflowfm/proter/metrics/SimMetricsPrinter.html","n":"SimMetricsPrinter","t":"class SimMetricsPrinter extends SimMetricsStringOutput","d":"com/workflowfm/proter/metrics/SimMetricsPrinter","k":"class"},
{"l":"com/workflowfm/proter/metrics/SimMetricsPrinter.html","n":"apply","t":"def apply(totalTicks: Long, aggregator: SimMetricsAggregator): Unit","d":"com/workflowfm/proter/metrics/SimMetricsPrinter","k":"def"},
{"l":"com/workflowfm/proter/metrics/SimMetricsStringOutput.html","n":"SimMetricsStringOutput","t":"trait SimMetricsStringOutput extends SimMetricsOutput","d":"com/workflowfm/proter/metrics/SimMetricsStringOutput","k":"trait"},
{"l":"com/workflowfm/proter/metrics/SimMetricsStringOutput.html","n":"nullValue","t":"val nullValue: String","d":"com/workflowfm/proter/metrics/SimMetricsStringOutput","k":"val"},
{"l":"com/workflowfm/proter/metrics/SimMetricsStringOutput.html","n":"resCSV","t":"def resCSV(separator: String)(m: ResourceMetrics): String","d":"com/workflowfm/proter/metrics/SimMetricsStringOutput","k":"def"},
{"l":"com/workflowfm/proter/metrics/SimMetricsStringOutput.html","n":"resHeader","t":"def resHeader(separator: String): String","d":"com/workflowfm/proter/metrics/SimMetricsStringOutput","k":"def"},
{"l":"com/workflowfm/proter/metrics/SimMetricsStringOutput.html","n":"resources","t":"def resources(aggregator: SimMetricsAggregator, separator: String, lineSep: String): String","d":"com/workflowfm/proter/metrics/SimMetricsStringOutput","k":"def"},
{"l":"com/workflowfm/proter/metrics/SimMetricsStringOutput.html","n":"simCSV","t":"def simCSV(separator: String)(m: SimulationMetrics): String","d":"com/workflowfm/proter/metrics/SimMetricsStringOutput","k":"def"},
{"l":"com/workflowfm/proter/metrics/SimMetricsStringOutput.html","n":"simHeader","t":"def simHeader(separator: String): String","d":"com/workflowfm/proter/metrics/SimMetricsStringOutput","k":"def"},
{"l":"com/workflowfm/proter/metrics/SimMetricsStringOutput.html","n":"simulations","t":"def simulations(aggregator: SimMetricsAggregator, separator: String, lineSep: String): String","d":"com/workflowfm/proter/metrics/SimMetricsStringOutput","k":"def"},
{"l":"com/workflowfm/proter/metrics/SimMetricsStringOutput.html","n":"taskCSV","t":"def taskCSV(separator: String, resSeparator: String)(m: TaskMetrics): String","d":"com/workflowfm/proter/metrics/SimMetricsStringOutput","k":"def"},
{"l":"com/workflowfm/proter/metrics/SimMetricsStringOutput.html","n":"taskHeader","t":"def taskHeader(separator: String): String","d":"com/workflowfm/proter/metrics/SimMetricsStringOutput","k":"def"},
{"l":"com/workflowfm/proter/metrics/SimMetricsStringOutput.html","n":"tasks","t":"def tasks(aggregator: SimMetricsAggregator, separator: String, lineSep: String, resSeparator: String): String","d":"com/workflowfm/proter/metrics/SimMetricsStringOutput","k":"def"},
{"l":"com/workflowfm/proter/metrics/SimNoOutput$.html","n":"SimNoOutput","t":"object SimNoOutput extends SimMetricsOutput","d":"com/workflowfm/proter/metrics/SimNoOutput$","k":"object"},
{"l":"com/workflowfm/proter/metrics/SimNoOutput$.html","n":"apply","t":"def apply(totalTicks: Long, aggregator: SimMetricsAggregator): Unit","d":"com/workflowfm/proter/metrics/SimNoOutput$","k":"def"},
{"l":"com/workflowfm/proter/metrics/SimulationMetrics.html","n":"SimulationMetrics","t":"class SimulationMetrics(name: String, started: Long, duration: Long, delay: Long, tasks: Int, cost: Double, result: Option[String])","d":"com/workflowfm/proter/metrics/SimulationMetrics","k":"class"},
{"l":"com/workflowfm/proter/metrics/SimulationMetrics.html","n":"addCost","t":"def addCost(c: Double): SimulationMetrics","d":"com/workflowfm/proter/metrics/SimulationMetrics","k":"def"},
{"l":"com/workflowfm/proter/metrics/SimulationMetrics.html","n":"addDelay","t":"def addDelay(d: Long): SimulationMetrics","d":"com/workflowfm/proter/metrics/SimulationMetrics","k":"def"},
{"l":"com/workflowfm/proter/metrics/SimulationMetrics.html","n":"addDuration","t":"def addDuration(d: Long): SimulationMetrics","d":"com/workflowfm/proter/metrics/SimulationMetrics","k":"def"},
{"l":"com/workflowfm/proter/metrics/SimulationMetrics.html","n":"done","t":"def done(res: String, time: Long): SimulationMetrics","d":"com/workflowfm/proter/metrics/SimulationMetrics","k":"def"},
{"l":"com/workflowfm/proter/metrics/SimulationMetrics.html","n":"task","t":"def task(task: TaskInstance): SimulationMetrics","d":"com/workflowfm/proter/metrics/SimulationMetrics","k":"def"},
{"l":"com/workflowfm/proter/metrics/SimulationMetrics$.html","n":"SimulationMetrics","t":"object SimulationMetrics","d":"com/workflowfm/proter/metrics/SimulationMetrics$","k":"object"},
{"l":"com/workflowfm/proter/metrics/SimulationMetrics$.html","n":"apply","t":"def apply(name: String, t: Long): SimulationMetrics","d":"com/workflowfm/proter/metrics/SimulationMetrics$","k":"def"},
{"l":"com/workflowfm/proter/metrics/TaskMetrics.html","n":"TaskMetrics","t":"class TaskMetrics(id: UUID, task: String, simulation: String, priority: Int, created: Long, started: Option[Long], duration: Long, cost: Double, resources: Seq[String], aborted: Boolean)","d":"com/workflowfm/proter/metrics/TaskMetrics","k":"class"},
{"l":"com/workflowfm/proter/metrics/TaskMetrics.html","n":"abort","t":"def abort(t: Long): TaskMetrics","d":"com/workflowfm/proter/metrics/TaskMetrics","k":"def"},
{"l":"com/workflowfm/proter/metrics/TaskMetrics.html","n":"addCost","t":"def addCost(addedCost: Double): TaskMetrics","d":"com/workflowfm/proter/metrics/TaskMetrics","k":"def"},
{"l":"com/workflowfm/proter/metrics/TaskMetrics.html","n":"delay","t":"def delay: Long","d":"com/workflowfm/proter/metrics/TaskMetrics","k":"def"},
{"l":"com/workflowfm/proter/metrics/TaskMetrics.html","n":"finished","t":"def finished: Option[Long]","d":"com/workflowfm/proter/metrics/TaskMetrics","k":"def"},
{"l":"com/workflowfm/proter/metrics/TaskMetrics.html","n":"fullName","t":"def fullName: String","d":"com/workflowfm/proter/metrics/TaskMetrics","k":"def"},
{"l":"com/workflowfm/proter/metrics/TaskMetrics.html","n":"start","t":"def start(st: Long): TaskMetrics","d":"com/workflowfm/proter/metrics/TaskMetrics","k":"def"},
{"l":"com/workflowfm/proter/metrics/TaskMetrics$.html","n":"TaskMetrics","t":"object TaskMetrics","d":"com/workflowfm/proter/metrics/TaskMetrics$","k":"object"},
{"l":"com/workflowfm/proter/metrics/TaskMetrics$.html","n":"apply","t":"def apply(task: TaskInstance): TaskMetrics","d":"com/workflowfm/proter/metrics/TaskMetrics$","k":"def"},
{"l":"com/workflowfm/proter/schedule.html","n":"com.workflowfm.proter.schedule","t":"package com.workflowfm.proter.schedule","d":"com/workflowfm/proter/schedule","k":"package"},
{"l":"com/workflowfm/proter/schedule/GreedyFCFSScheduler.html","n":"GreedyFCFSScheduler","t":"class GreedyFCFSScheduler(initialTasks: TaskInstance*) extends QueueScheduler with GreedyScheduler","d":"com/workflowfm/proter/schedule/GreedyFCFSScheduler","k":"class"},
{"l":"com/workflowfm/proter/schedule/GreedyPriorityScheduler.html","n":"GreedyPriorityScheduler","t":"class GreedyPriorityScheduler(initialTasks: TaskInstance*) extends PriorityScheduler with GreedyScheduler","d":"com/workflowfm/proter/schedule/GreedyPriorityScheduler","k":"class"},
{"l":"com/workflowfm/proter/schedule/GreedyScheduler.html","n":"GreedyScheduler","t":"trait GreedyScheduler extends Scheduler","d":"com/workflowfm/proter/schedule/GreedyScheduler","k":"trait"},
{"l":"com/workflowfm/proter/schedule/GreedyScheduler.html","n":"findNextTasks","t":"def findNextTasks(idleResources: Map[String, TaskResource], tasks: Iterable[TaskInstance], result: Queue[TaskInstance]): Seq[TaskInstance]","d":"com/workflowfm/proter/schedule/GreedyScheduler","k":"def"},
{"l":"com/workflowfm/proter/schedule/LookaheadScheduler.html","n":"LookaheadScheduler","t":"class LookaheadScheduler(initialTasks: TaskInstance*) extends PriorityScheduler","d":"com/workflowfm/proter/schedule/LookaheadScheduler","k":"class"},
{"l":"com/workflowfm/proter/schedule/LookaheadScheduler.html","n":"completed","t":"val completed: Set[(UUID, Long)]","d":"com/workflowfm/proter/schedule/LookaheadScheduler","k":"val"},
{"l":"com/workflowfm/proter/schedule/LookaheadScheduler.html","n":"findNextTasks","t":"def findNextTasks(currentTime: Long, resourceMap: Map[String, TaskResource], schedules: Map[String, Schedule], tasks: SortedSet[TaskInstance], scheduledThisIter: Seq[(UUID, Long)], lookaheadSetThisIter: Lookahead, result: Queue[TaskInstance]): Seq[TaskInstance]","d":"com/workflowfm/proter/schedule/LookaheadScheduler","k":"def"},
{"l":"com/workflowfm/proter/schedule/LookaheadScheduler.html","n":"lookaheadObjects","t":"val lookaheadObjects: Map[String, Lookahead]","d":"com/workflowfm/proter/schedule/LookaheadScheduler","k":"val"},
{"l":"com/workflowfm/proter/schedule/PriorityScheduler.html","n":"PriorityScheduler","t":"class PriorityScheduler(using ordering: Ordering[TaskInstance]) extends Scheduler","d":"com/workflowfm/proter/schedule/PriorityScheduler","k":"class"},
{"l":"com/workflowfm/proter/schedule/PriorityScheduler.html","n":"tasks","t":"val tasks: SortedSet[TaskInstance]","d":"com/workflowfm/proter/schedule/PriorityScheduler","k":"val"},
{"l":"com/workflowfm/proter/schedule/ProterScheduler.html","n":"ProterScheduler","t":"class ProterScheduler(initialTasks: TaskInstance*) extends PriorityScheduler","d":"com/workflowfm/proter/schedule/ProterScheduler","k":"class"},
{"l":"com/workflowfm/proter/schedule/ProterScheduler.html","n":"findNextTasks","t":"def findNextTasks(currentTime: Long, resourceMap: Map[String, TaskResource], schedules: Map[String, Schedule], tasks: SortedSet[TaskInstance], result: Queue[TaskInstance]): Seq[TaskInstance]","d":"com/workflowfm/proter/schedule/ProterScheduler","k":"def"},
{"l":"com/workflowfm/proter/schedule/QueueScheduler.html","n":"QueueScheduler","t":"trait QueueScheduler extends Scheduler","d":"com/workflowfm/proter/schedule/QueueScheduler","k":"trait"},
{"l":"com/workflowfm/proter/schedule/QueueScheduler.html","n":"tasks","t":"val tasks: Queue[TaskInstance]","d":"com/workflowfm/proter/schedule/QueueScheduler","k":"val"},
{"l":"com/workflowfm/proter/schedule/Schedule.html","n":"Schedule","t":"class Schedule(tasks: List[(Long, Long)])","d":"com/workflowfm/proter/schedule/Schedule","k":"class"},
{"l":"com/workflowfm/proter/schedule/Schedule.html","n":"+","t":"def +(start: Long, end: Long): Option[Schedule]","d":"com/workflowfm/proter/schedule/Schedule","k":"def"},
{"l":"com/workflowfm/proter/schedule/Schedule.html","n":"++","t":"def ++(s: Schedule): Schedule","d":"com/workflowfm/proter/schedule/Schedule","k":"def"},
{"l":"com/workflowfm/proter/schedule/Schedule.html","n":"+>","t":"def +>(start: Long, end: Long): Schedule","d":"com/workflowfm/proter/schedule/Schedule","k":"def"},
{"l":"com/workflowfm/proter/schedule/Schedule.html","n":"+>","t":"def +>(startTime: Long, t: TaskInstance): Schedule","d":"com/workflowfm/proter/schedule/Schedule","k":"def"},
{"l":"com/workflowfm/proter/schedule/Schedule.html","n":"?","t":"def ?(currentTime: Long, t: TaskInstance): Long","d":"com/workflowfm/proter/schedule/Schedule","k":"def"},
{"l":"com/workflowfm/proter/schedule/Schedule.html","n":"isValid","t":"def isValid: Boolean","d":"com/workflowfm/proter/schedule/Schedule","k":"def"},
{"l":"com/workflowfm/proter/schedule/Schedule$.html","n":"Schedule","t":"object Schedule","d":"com/workflowfm/proter/schedule/Schedule$","k":"object"},
{"l":"com/workflowfm/proter/schedule/Schedule$.html","n":"add","t":"def add(start: Long, end: Long, tasks: List[(Long, Long)], result: Queue[(Long, Long)]): Option[List[(Long, Long)]]","d":"com/workflowfm/proter/schedule/Schedule$","k":"def"},
{"l":"com/workflowfm/proter/schedule/Schedule$.html","n":"apply","t":"def apply(): Schedule","d":"com/workflowfm/proter/schedule/Schedule$","k":"def"},
{"l":"com/workflowfm/proter/schedule/Schedule$.html","n":"apply","t":"def apply(r: TaskResource): Schedule","d":"com/workflowfm/proter/schedule/Schedule$","k":"def"},
{"l":"com/workflowfm/proter/schedule/Schedule$.html","n":"fit","t":"def fit(start: Long, duration: Long, tasks: List[(Long, Long)]): Long","d":"com/workflowfm/proter/schedule/Schedule$","k":"def"},
{"l":"com/workflowfm/proter/schedule/Schedule$.html","n":"fitInGaps","t":"def fitInGaps(start: Long, end: Long, gaps: List[(Long, Long)], result: Queue[(Long, Long)]): Option[List[(Long, Long)]]","d":"com/workflowfm/proter/schedule/Schedule$","k":"def"},
{"l":"com/workflowfm/proter/schedule/Schedule$.html","n":"isValid","t":"def isValid(gaps: List[(Long, Long)], end: Long): Boolean","d":"com/workflowfm/proter/schedule/Schedule$","k":"def"},
{"l":"com/workflowfm/proter/schedule/Schedule$.html","n":"merge","t":"def merge(g1: List[(Long, Long)], g2: List[(Long, Long)], result: Queue[(Long, Long)]): List[(Long, Long)]","d":"com/workflowfm/proter/schedule/Schedule$","k":"def"},
{"l":"com/workflowfm/proter/schedule/Schedule$.html","n":"mergeGaps","t":"def mergeGaps(g1: List[(Long, Long)], g2: List[(Long, Long)], result: Queue[(Long, Long)]): List[(Long, Long)]","d":"com/workflowfm/proter/schedule/Schedule$","k":"def"},
{"l":"com/workflowfm/proter/schedule/Schedule$.html","n":"mergeSchedules","t":"def mergeSchedules(schedules: Seq[Schedule]): Schedule","d":"com/workflowfm/proter/schedule/Schedule$","k":"def"},
{"l":"com/workflowfm/proter/schedule/Scheduler.html","n":"Scheduler","t":"trait Scheduler","d":"com/workflowfm/proter/schedule/Scheduler","k":"trait"},
{"l":"com/workflowfm/proter/schedule/Scheduler.html","n":"addTask","t":"def addTask(task: TaskInstance): Unit","d":"com/workflowfm/proter/schedule/Scheduler","k":"def"},
{"l":"com/workflowfm/proter/schedule/Scheduler.html","n":"complete","t":"def complete(task: TaskInstance, time: Long): Unit","d":"com/workflowfm/proter/schedule/Scheduler","k":"def"},
{"l":"com/workflowfm/proter/schedule/Scheduler.html","n":"getNextTasks","t":"def getNextTasks(currentTime: Long, resourceMap: Map[String, TaskResource]): Seq[TaskInstance]","d":"com/workflowfm/proter/schedule/Scheduler","k":"def"},
{"l":"com/workflowfm/proter/schedule/Scheduler.html","n":"getTasks","t":"def getTasks(): Iterable[TaskInstance]","d":"com/workflowfm/proter/schedule/Scheduler","k":"def"},
{"l":"com/workflowfm/proter/schedule/Scheduler.html","n":"isIdleResource","t":"def isIdleResource(r: String, resourceMap: Map[String, TaskResource]): Boolean","d":"com/workflowfm/proter/schedule/Scheduler","k":"def"},
{"l":"com/workflowfm/proter/schedule/Scheduler.html","n":"noMoreTasks","t":"def noMoreTasks(): Boolean","d":"com/workflowfm/proter/schedule/Scheduler","k":"def"},
{"l":"com/workflowfm/proter/schedule/Scheduler.html","n":"removeLookahead","t":"def removeLookahead(simulation: String): Unit","d":"com/workflowfm/proter/schedule/Scheduler","k":"def"},
{"l":"com/workflowfm/proter/schedule/Scheduler.html","n":"removeSimulation","t":"def removeSimulation(simulation: String): Unit","d":"com/workflowfm/proter/schedule/Scheduler","k":"def"},
{"l":"com/workflowfm/proter/schedule/Scheduler.html","n":"removeTask","t":"def removeTask(task: TaskInstance): Unit","d":"com/workflowfm/proter/schedule/Scheduler","k":"def"},
{"l":"com/workflowfm/proter/schedule/Scheduler.html","n":"setLookahead","t":"def setLookahead(simulation: String, obj: Lookahead): Unit","d":"com/workflowfm/proter/schedule/Scheduler","k":"def"},
{"l":"com/workflowfm/proter/schedule/StrictFCFSScheduler.html","n":"StrictFCFSScheduler","t":"class StrictFCFSScheduler(initialTasks: TaskInstance*) extends QueueScheduler with StrictScheduler","d":"com/workflowfm/proter/schedule/StrictFCFSScheduler","k":"class"},
{"l":"com/workflowfm/proter/schedule/StrictPriorityScheduler.html","n":"StrictPriorityScheduler","t":"class StrictPriorityScheduler(initialTasks: TaskInstance*) extends PriorityScheduler with StrictScheduler","d":"com/workflowfm/proter/schedule/StrictPriorityScheduler","k":"class"},
{"l":"com/workflowfm/proter/schedule/StrictScheduler.html","n":"StrictScheduler","t":"trait StrictScheduler extends Scheduler","d":"com/workflowfm/proter/schedule/StrictScheduler","k":"trait"},
{"l":"com/workflowfm/proter/schedule/StrictScheduler.html","n":"findNextTasks","t":"def findNextTasks(idleResources: Map[String, TaskResource], tasks: Iterable[TaskInstance], result: Queue[TaskInstance]): Seq[TaskInstance]","d":"com/workflowfm/proter/schedule/StrictScheduler","k":"def"},
{"l":"docs/index.html","n":"proter-root","t":"proter-root","d":"","k":"static"}];