name: Publish server jar and Docker image on release

on:
  release:
    types:
      - created

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: workflowfm/proter-server

jobs:
  server:
    name: Build and release server as Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache
        uses: coursier/cache-action@v6

      - name: Build
        run: sbt 'proter-server / assembly'

      - name: Upload distribution to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: proter-server/target/scala-3.1.0/proter-server_*.jar
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

      - name: Rename jar
        run: mv proter-server/target/scala-3.1.0/proter-server_*.jar proter-server/target/scala-3.1.0/proter-server.jar 

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: proter-server/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: Cleanup
        run: rm -rf proter-server/target/scala-3.1.0/proter-server*.jar
